# Generated by Django 5.1 on 2024-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_column='FilePath', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('language', models.IntegerField(db_column='Language')),
                ('notify', models.BooleanField(db_column='Notify')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Settings',
                'managed': False,
            },
        ),
    ]
