# Generated by Django 5.1 on 2024-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExams',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('exam_id', models.BigIntegerField(db_column='ExamId')),
                ('progress', models.IntegerField(db_column='Progress')),
                ('is_finished', models.BooleanField(db_column='IsFinished')),
            ],
            options={
                'db_table': 'UserExams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubjects',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('subject_id', models.BigIntegerField(db_column='SubjectId')),
                ('progress', models.IntegerField(db_column='Progress')),
                ('is_bought', models.BooleanField(db_column='IsBought')),
                ('is_favorite', models.BooleanField(db_column='IsFavorite')),
            ],
            options={
                'db_table': 'UserSubjects',
                'managed': False,
            },
        ),
    ]
