# Generated by Django 5.1 on 2024-09-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userexams_usersubjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AlterModelTable(
            name='usersubjects',
            table='UserCourses',
        ),
    ]
