# Generated by Django 5.1 on 2024-08-25 09:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('username', models.CharField(blank=True, db_column='FirstName', max_length=150)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=150)),
                ('password', models.CharField(db_column='Password', max_length=128)),
                ('score', models.IntegerField(db_column='Score', default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
