# Generated by Django 5.1 on 2024-09-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('language', models.CharField(db_column='Language', max_length=50)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(blank=True, db_column='SellPrice', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_column='FilePath', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Icons',
                'managed': False,
            },
        ),
    ]
