# Generated by Django 5.1 on 2024-09-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('language', models.CharField(db_column='Language')),
                ('notify', models.BooleanField(db_column='Notify')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
            ],
            options={
                'db_table': 'Settings',
                'managed': False,
            },
        ),
    ]
